openapi: 3.0.1
info:
  title: Todo and Notes API
  description: API for managing todo items and notes
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /v1/todo:
    post:
      summary: Create a new todo item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
      responses:
        '200':
          description: Todo item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomSuccessResponse_TaskEntity'
    
    get:
      summary: Get paginated list of todo items
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: perPage
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - name: status
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: List of todo items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetNewsResponse'
    
    patch:
      summary: Update status of all todo items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeStatusTodoRequest'
      responses:
        '200':
          description: Status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseSuccessResponse'
    
    delete:
      summary: Delete all completed todo items
      responses:
        '200':
          description: Completed todo items deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseSuccessResponse'

  /v1/todo/status/{id}:
    patch:
      summary: Update status of a specific todo item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeStatusTodoRequest'
      responses:
        '200':
          description: Todo item status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseSuccessResponse'

  /v1/todo/text/{id}:
    patch:
      summary: Update text of a specific todo item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeTextTodoRequest'
      responses:
        '200':
          description: Todo item text updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseSuccessResponse'

  /v1/notes:
    post:
      summary: Create a new note
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNoteRequest'
      responses:
        '200':
          description: Note created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomSuccessResponse_NoteResponse'
    
    get:
      summary: Get paginated list of notes
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: size
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 10
      responses:
        '200':
          description: List of notes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomSuccessResponse_List_NoteResponse_'

  /v1/notes/{id}:
    get:
      summary: Get a specific note by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Note details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomSuccessResponse_NoteResponse'
    
    patch:
      summary: Update a specific note
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNoteRequest'
      responses:
        '200':
          description: Note updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomSuccessResponse_NoteResponse'
    
    delete:
      summary: Delete a specific note
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Note deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseSuccessResponse'

components:
  schemas:
    # Request schemas
    CreateTodoRequest:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          minLength: 3
          maxLength: 160
          description: The text content of the todo item
    
    ChangeStatusTodoRequest:
      type: object
      required:
        - status
      properties:
        status:
          type: boolean
          description: The new status of the todo item
    
    ChangeTextTodoRequest:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          minLength: 3
          maxLength: 160
          description: The new text content for the todo item
    
    CreateNoteRequest:
      type: object
      required:
        - title
        - content
      properties:
        title:
          type: string
          maxLength: 100
          description: The title of the note
        content:
          type: string
          maxLength: 1000
          description: The content of the note
    
    UpdateNoteRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 100
          description: The new title of the note (optional)
        content:
          type: string
          maxLength: 1000
          description: The new content of the note (optional)
    
    # Response schemas
    BaseSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        statusCode:
          type: integer
          example: 1
        message:
          type: string
          example: "Success"
    
    CustomSuccessResponse_TaskEntity:
      allOf:
        - $ref: '#/components/schemas/BaseSuccessResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/TaskEntity'
    
    CustomSuccessResponse_NoteResponse:
      allOf:
        - $ref: '#/components/schemas/BaseSuccessResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/NoteResponse'
    
    CustomSuccessResponse_List_NoteResponse_:
      allOf:
        - $ref: '#/components/schemas/BaseSuccessResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/NoteResponse'
    
    TaskEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
        status:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    
    NoteResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    
    GetNewsResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/TaskEntity'
        pageNumber:
          type: integer
        pageSize:
          type: integer
        totalPages:
          type: integer
        totalElements:
          type: integer
